server:
  port: 9010
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: http://1.15.242.150:8848
        namespace: 56b17a5f-0aef-4214-b42b-37805467ba0c
        group: TEST_GROUP